/*
 * This source file was generated by the Gradle 'init' task
 */
package uts;

import uts.views.KendaraanView;

public class App {

    public static void main(String[] args) {
        KendaraanView kendaraanView = new KendaraanView();

        kendaraanView.render();
    }
}
